import{i as h,S as m,a as g}from"./assets/vendor-527658dd.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();function n(t){h.error({title:"Error",message:t,position:"topRight"})}function d(){const t=document.querySelector(".gallery");t.innerHTML=""}function f(t){const r=document.querySelector(".gallery");t.forEach(s=>{const e=document.createElement("div");e.classList.add("card"),e.innerHTML=`
            <a href="${s.largeImageURL}" data-lightbox="image">
                <img src="${s.webformatURL}" alt="${s.tags}">
            </a>
            <div class="details">
                <span>Likes: ${s.likes}</span>
                <span>Views: ${s.views}</span>
                <span>Comments: ${s.comments}</span>
                <span>Downloads: ${s.downloads}</span>
            </div>
        `,r.appendChild(e)}),new m(".gallery a").refresh()}const u=document.querySelector("#search-form"),i=document.querySelector(".loader");let c=1;u.addEventListener("submit",async t=>{t.preventDefault();const r=u.querySelector("input").value.trim();if(!r){n("Please enter a search query");return}i.style.display="block";try{const a=await p(r,c);a.length===0?(d(),n("Sorry, there are no images matching your search query. Please try again!")):(d(),f(a),c=1,y.style.display="block")}catch(a){n(a.message)}finally{i.style.display="none"}});async function p(t,r){const e=`https://pixabay.com/api/?key=42739945-76af92f6f6e2beeeb6ab8bd95&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const o=await g.get(e);if(o.status!==200)throw new Error("Failed to fetch images");return o.data.hits}catch{throw new Error("Failed to fetch images")}}const y=document.querySelector("#load-more-btn");y.addEventListener("click",async()=>{const t=u.querySelector("input").value.trim();if(!t){d(),n("Please enter a search query");return}i.style.display="block";try{c++;const r=await p(t,c);r.length===0?(y.style.display="none",n("We're sorry, but you've reached the end of search results.")):(f(r),b())}catch(r){n(r.message)}finally{i.style.display="none"}});function b(){const t=document.querySelector(".card").offsetHeight;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
